# -*- coding: utf-8 -*-
"""4_Effect of delayed gastrostomy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ce11efzIKeqIG45rLa9gjcSj6OFktLLI
"""

# Load packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

"""# 1. Preprocessing"""

# Read datasets needed
from google.colab import files 
uploaded = files.upload()

import io
feature = pd.read_csv(io.BytesIO(uploaded['0913_X_imputed.csv'])) 
optimal_gastro = pd.read_csv(io.BytesIO(uploaded['0913_optimal_target.csv']))   # optimal_gastro means 'time to dietary consistency change'
real_gastro = pd.read_csv(io.BytesIO(uploaded['0913_real_target.csv']))    # real_gastro means whether a patient got the actual gastrostomy or not
surv =  pd.read_csv(io.BytesIO(uploaded['survival.csv']))

optimal_gastro.drop(columns='Unnamed: 0', inplace=True)
real_gastro.drop(columns='Unnamed: 0', inplace=True)
feature.drop(columns='Unnamed: 0', inplace=True)

feature['mean_Q1_2_3_mouth'] = feature['mean_Q1_Speech'] + feature['mean_Q2_Salivation'] + feature['mean_Q3_Swallowing']

pip install lifelines

print("There are",len(feature),"patients with feature") # There are 4088 patients with feature
print("There are",len(optimal_gastro),"patients with opt-gas value") # There are 4523 patients with opt-gas value
print("There are",len(real_gastro),"patients with real-gas value") # There are 5534 patients with real-gas value
feature_real = feature.merge(real_gastro, on='SubjectID', how='inner')
print("There are",len(feature_real),"patients with feature & real value 1:",len(feature_real[feature_real['status_real']==1]),"0:", len(feature_real[feature_real['status_real']==0])) # There are 3289 patients with feature & real value 1: 598 0: 2691

"""## 1) Calculate predicted optimal time for patients"""

# train data for model predicting optimal gas time
feature_opt = feature.merge(optimal_gastro, on='SubjectID', how='inner')
feature_opt.query('time_opt !=0', inplace=True)

df_train = feature_opt.copy()
df_train = df_train[['Age', 'onset_delta', 'fvc_mean', 'mean_Q1_2_3_mouth', 'mean_Q7_Turning_in_Bed',
       'alsfrs_total_slope', 'slope_Q3_Swallowing', 'weight_slope', 'status_opt', 'time_opt']]
df_train

# input data for trained model
df_input = feature_real[['Age', 'onset_delta', 'fvc_mean', 'mean_Q1_2_3_mouth', 'mean_Q7_Turning_in_Bed',
       'alsfrs_total_slope', 'slope_Q3_Swallowing', 'weight_slope']]
df_input

# Train model
from lifelines import CoxPHFitter
cph = CoxPHFitter(penalizer=0.1, l1_ratio=0.2)
cph.fit(df_train, 'time_opt', event_col='status_opt')

# median optimal time is predicted by trained model
cph_median = pd.concat([feature_real['SubjectID'],cph.predict_median(df_input)], axis=1)
cph_median.columns = ['SubjectID', 'predicted_opt']
cph_median_without_inf = cph_median[cph_median['predicted_opt']!=np.inf]
feat_real_optpred = feature_real.merge(cph_median_without_inf, on='SubjectID', how='inner')
feat_real_optpred['time_diff'] = feat_real_optpred['time_real']-feat_real_optpred['predicted_opt']
print('There are ', len(cph_median[cph_median['predicted_opt']==np.inf]), 'inf values which have been removed')
 # There are  15 inf values which have been removed
print(cph_median_without_inf)

"""## 2) Merge (actual gas/ predicted optimal gas / survival) & Define 'Time difference'"""

feat_real_optpred = feature_real.merge(cph_median_without_inf, on='SubjectID', how='inner')
feat_real_optpred['time_diff'] = feat_real_optpred['time_real']-feat_real_optpred['predicted_opt'] # Time difference is defined as time differece between 'predicted opt' and 'time real'
feat_real_optpred # 3274 data

feat_td_surv = feat_real_optpred.merge(surv, on='SubjectID', how='inner') # 'td' states for time difference
feat_td_surv #3102 data

"""# 2. Analysis on Survival effect of 'Time difference'"""

# Filter with (time real, predicted opt < time event for survival); those who have survival follow-ups after their own gastrostomy time
feat_td_surv_filtered = feat_td_surv[feat_td_surv['time_real']<feat_td_surv['time_event']]
feat_td_surv_filtered = feat_td_surv_filtered[feat_td_surv_filtered['predicted_opt']<feat_td_surv_filtered['time_event']]
print(len(feat_td_surv_filtered), 'are left, while', len(feat_td_surv)-len(feat_td_surv_filtered), "are removed for censoring") # 577 are left, while 2525 are removed for censoring

plt.figure(figsize=(8, 3))
sns.histplot(feat_td_surv_filtered['time_diff'])

"""## 1) Brief observation: Correlation between survival time and time difference"""

scat_df = feat_td_surv_filtered.query('status==1 and status_real==1')
fig, ax = plt.subplots(figsize=(6,5))
sns.regplot(x=scat_df['time_diff'], y=scat_df['time_event'], fit_reg=True) 
plt.xlabel('Time difference', fontsize=9)
plt.ylabel('Survival time', fontsize=9)
plt.show() # downward sloping

"""## 2) Group estimation by Kaplan-Meier"""

f_t_s_f_real_1 = feat_td_surv_filtered[feat_td_surv_filtered['status_real']==1]
print(f_t_s_f_real_1['time_diff'].describe())

# 25%      -38.000000
# 50%       13.000000
# 75%       67.000000

# Early / Medium / Late group with 25/50/25 percentile
feature_early= f_t_s_f_real_1[f_t_s_f_real_1['time_diff']<= -38]
feature_medium= f_t_s_f_real_1.query('(time_diff > -38) and (time_diff <= 67)')
feature_late= f_t_s_f_real_1[feat_td_surv_filtered['time_diff']> 67]

early_list= list(feature_early['SubjectID'])
medium_list= list(feature_medium['SubjectID'])
late_list= list(feature_late['SubjectID'])+list(feat_td_surv_filtered[feat_td_surv_filtered['status_real']==0].query('time_diff >67')['SubjectID']) # Patients in (status_real, status_opt) = (0. 1)  who satisfied criterion were added for late group
 
surv_early = feat_td_surv_filtered.query("SubjectID == {0}".format(early_list))
surv_medium = feat_td_surv_filtered.query("SubjectID == {0}".format(medium_list))
surv_late = feat_td_surv_filtered.query("SubjectID == {0}".format(late_list))

print("Subjects are categorized  ", len(surv_early), "(25% Early)", len(surv_medium), '(50% Medium)', len(surv_late), '(25+a% Late)')
 # Subjects are categorized   101 (25% Early) 195 (50% Medium) 163 (25+a% Late)

# Check the proportion of censored data in each group
event_distribution_early = pd.DataFrame(surv_early[['status']].value_counts()).reset_index()
event_distribution_early.columns = ['status', 'count']
event_distribution_early['status'] = event_distribution_early['status'].astype('bool')
event_distribution_early = event_distribution_early.replace({'status': {False:'0 (censored)', True:'1 (occured)'}})
print(event_distribution_early)   # 55 censored, 46 uncensored

event_distribution_medium = pd.DataFrame(surv_medium[['status']].value_counts()).reset_index()
event_distribution_medium.columns = ['status', 'count']
event_distribution_medium['status'] = event_distribution_medium['status'].astype('bool')
event_distribution_medium = event_distribution_medium.replace({'status': {False:'0 (censored)', True:'1 (occured)'}})
print(event_distribution_medium)   # 109 censored, 86 uncensored

event_distribution_late = pd.DataFrame(surv_late[['status']].value_counts()).reset_index()
event_distribution_late.columns = ['status', 'count']
event_distribution_late['status'] = event_distribution_late['status'].astype('bool')
event_distribution_late = event_distribution_late.replace({'status': {False:'0 (censored)', True:'1 (occured)'}})
print(event_distribution_late)   # 92 censored, 71 uncensored

from lifelines import KaplanMeierFitter
plt.figure(figsize=(8, 6))
kmf = KaplanMeierFitter()

kmf.fit(surv_early["time_event"], surv_early["status"], label="early",alpha=1)
ax_kmf = kmf.plot(linewidth=3)
kmf.fit(surv_medium["time_event"], surv_medium["status"], label="medium",alpha=1)
ax_kmf = kmf.plot(ax=ax_kmf, color='#FFB291',linewidth=3)
kmf.fit(surv_late["time_event"], surv_late["status"], label="late",alpha=1)
ax_kmf = kmf.plot(ax=ax_kmf, linewidth=3)

ax_kmf.set_ylim(0,1.02)
ax_kmf.set_xlim()
ax_kmf.set_xlabel('time (days)', fontsize=11)
ax_kmf.set_ylabel('survival function, $\hat{S}(t)$', fontsize=13)
plt.title('Group estimation by Kaplan-Meier', fontsize=13)
plt.show()
print('The plot above suggests a time-varying effect of Time difference for survival event.')

from lifelines.statistics import logrank_test
logrank_test(surv_early["time_event"], surv_late["time_event"], surv_early["status"], surv_late["status"]).p_value
# p_value = 0.00010714354349287425